# This controls sops for the whole repo
keys:
  - &primary age18t746dc2xxr4ul5t4wthnrmhrmhuukmgmh3u4ke2rmxca56anarsesw4jy

creation_rules:
  - path_regex: .*/secrets/.*\.env$
    key_groups:
      - age:
          - *primary
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *primary


#keys:
#  - &primary age18t746dc2xxr4ul5t4wthnrmhrmhuukmgmh3u4ke2rmxca56anarsesw4jy
#creation_rules:
#  - path_regex: secrets/secrets.yaml$
#    key_groups:
#      - age:
#        - *primary

